name: Matrix Workflow
on: workflow_dispatch
jobs:
  deploy:
        if: github.ref == 'refs/heads/main'
        strategy:
          fail-fast: false
          max-parallel: 2
          matrix:
            os: [ubuntu-latest, windows-latest]
            images: [hello-world, alpine]
            include:
            - os: amd64/alpine
              images: ubuntu:latest
            exclude:
            - os: windows-latest
              images: alpine
        runs-on: ${{ matrix.os }}
        steps:
        - name: welcome message
          run: echo "welcome to the GA actions"
        - name: Run image
          run: docker run --rm ${{ matrix.images }}

